<?xml version="1.0" encoding="utf-8" standalone="yes" ?>

<!DOCTYPE root[

  <!ELEMENT visitor (name,login,phone,email)>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST name
    type (admin | user)
  >
  <!ELEMENT login (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT sport EMPTY>
  <!ATTLIST sport
    type (skateboard | soccer | golf)
  >

  <!ELEMENT person (one,two,also,there)>
  <!ELEMENT one (#PCDATA)>
  <!ELEMENT two (#PCDATA)>
  <!ELEMENT also (#PCDATA)>
  <!ELEMENT there (#PCDATA)>
  <!ELEMENT self_close EMPTY>
  <!ELEMENT attribs (#PCDATA)>
  <!ATTLIST attribs
    attr (val1 | val2 | val3)
  >

]>

<root>

  <visitor>
    <name level="admin">John Doe</name>
    <login>jdoe</login>
    <phone>555-1212</phone>
    <email>jdoe@verb.ink</email>
    <sport type="skateboard"/>
  </visitor>

  <visitor>
    <name level="user">Smithy Mars</name>
    <login>smithymars</login>
    <phone>555-1515</phone>
    <email>smithy@inkisaverb.com</email>
    <sport type="soccer"/>
  </visitor>

  <person>
    <one>value 1</one>
    <two>value 2</two>
    <also>also value</also>
    <there>there value</there>
    <self_close/>
    <attribs attr="val1">some attributed thing</attribs>
  </person>

</root>
